feat(web): Add hold open toggle
overextended/ox_doorlock pull request #141
Opened 2023-05-21 06:55 UTC by jag3dagster

- Add toggle to UI to allow a door to be held open once unlocked, useful for MLOs that have drive-thru windows but bad door tuning amongst other situations

- Note: This was authored by @Vicken52. He asked me to submit the PR as I already had the repro setup locally.

2023-05-22 21:17 UTC, LukeWasTakenn approved these changes

2023-05-25 04:30 UTC, thelindat requested changes

2023-05-25 04:30 UTC, thelindat commented on client/main.lua
> +		if door.holdOpen then DoorSystemSetHoldOpen(double[1].hash, door.state == 0); DoorSystemSetHoldOpen(double[2].hash, door.state == 0) end
Ugly one-liner.

```lua
if door.holdOpen then
    DoorSystemSetHoldOpen(double[1].hash, door.state == 0)
    DoorSystemSetHoldOpen(double[2].hash, door.state == 0)
end
```

2023-05-25 04:30 UTC, thelindat commented on web/src/layouts/settings/views/general/components/Switches.tsx
> +          infoCircle="Sets whether the targeting door should be held open"
targeting door?

2023-05-25 04:32 UTC, thelindat commented
Should this maybe only be an option for automatic doors?

2023-05-26 19:40 UTC, jag3dagster commented
> Should this maybe only be an option for automatic doors?

It works for regular doors as well. There are cases where someone may want to 'prop open a door' as an invite for people to come into a business or something.

2023-05-28 05:34 UTC, merged